_target_: rewards.reward.Reward

root_dir: rewards

prop_cfg:
  - name: tsenn_static_dielectric_layered_uniaxial
    calculator:
      _target_: rewards.calculators.TSENNStaticDielectric
      root_dir: rewards/tsenn_static_dielectric_layered_uniaxial
      task: static_dielectric
      model_path: ${hydra:runtime.cwd}/data/surrogates/TSENN_static_dielectric_tensor.torch
      config_path: ${hydra:runtime.cwd}/data/surrogates/TSENN_static_dielectric_tensor.yaml
      device: ${device}
      batch_size: 16
      scalar_mode: layered_uniaxial
      standardize_structure: refined
      standardize_symprec: 0.01
    target: ascending
    minv: 0.0
    maxv: 0.20

reward_threshold: 0.75
