_target_: rewards.reward.Reward

root_dir: rewards

prop_cfg:
  - name: tsenn_static_dielectric
    calculator:
      _target_: rewards.calculators.TSENNStaticDielectric
      root_dir: rewards/tsenn_static_dielectric
      task: static_dielectric
      model_path: ${hydra:runtime.cwd}/data/surrogates/TSENN_static_dielectric_tensor.torch
      device: ${device}
      batch_size: 16
      r_max: 6.0
      out_dim: 1
      em_dim: 64
      lmax: 2
      layers: 2
      mul: 32
      num_neighbors: 59.902574690065045
      scale_0e: 8.20143833581954
      scale_2e: 0.6969301341467804
      dropout_prob: 0.4
      use_batch_norm: false
      scalar_mode: trace_mean
      component_i: 0
      component_j: 0
    target: ascending
    minv: 35.0
    maxv: 120.0

reward_threshold: 0.875
