_target_: rewards.reward.Reward

root_dir: rewards

prop_cfg:
  - name: tsenn_static_dielectric
    calculator:
      _target_: rewards.calculators.TSENNStaticDielectric
      root_dir: rewards/tsenn_static_dielectric
      task: static_dielectric
      model_path: ${hydra:runtime.cwd}/data/surrogates/TSENN_static_dielectric_tensor.torch
      config_path: ${hydra:runtime.cwd}/data/surrogates/TSENN_static_dielectric_tensor.yaml
      device: ${device}
      batch_size: 16
      scalar_mode: trace_mean
      component_i: 0
      component_j: 0
    target: ascending
    minv: 35.0
    maxv: 120.0

reward_threshold: 0.875
